# Module descriptor for deki-engine auto-discovery
set(MODULE_DISPLAY_NAME "Rendering")
set(MODULE_PREFIX "DekiRendering")
set(MODULE_UPPER "RENDERING")
set(MODULE_TARGET "deki-rendering")
set(MODULE_FILE_PREFIX "Rendering")
set(MODULE_HAS_SYSTEM_INIT ON)
set(MODULE_NEEDS_IMGUI ON)
set(MODULE_LINK_DEPS deki-editor)
set(MODULE_ENTRY DekiRenderingModule.cpp)
